# Python review

Goals:
- recall basic Python vocabulary 
- practice markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific tasks in our programs. 

**NumPy**: 
- core library for numerical computing in Python
- many other libraries use NumPy arraysas building blocks
- computations on Numpy are optimized for speed and memory usage

In [3]:
import numpy as np  

## Variables 

**variable**: name assigned to a particular object in Python

In [4]:
# Assign a small array to variable a
a = np.array( [ [1,1,2],[3,5,8] ] )

In [5]:
# Run cell with the variable to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use 'print' to show the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object**: bubdle of *properties* and *actions* about something specific. 

Example: 
    Object: data frame
    Properties: number of rows, names of columns, date created
    Actions: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.
In practice, we can often  variable  and object interchangeably.

## Types

Every object in Python has a **type**. The type tell us what kind of object it is.
We can also call the type of an object, the class of an object and they mean what kind of object we have.

In [7]:
print(a)

#Check the type/classof a variable/object by using the 'type' function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [9]:
print(a[0,0])

#type on an enrty of the array by indexing 
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not the standard integer type. This is telling us that 1 is an integer stored as a 64-bit number.

In [10]:
a[1,1]

5

Functions take in a set of **arguments** and they creat an output.

argument = parameter.

We can ask information about a function by writing `?function`

In [11]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two types of arguments:

- **non-optional argument**: arguments you *need* to specify for the function to work.
- **optional arguments**: arguments are pre-filled with a default value. You can override them. Optional arguments appear inside the parenthesis in the form `optional_argument=default_value`

In [13]:
print('changing the default end argument', end = ' :)')

changing the default end argument :)

## Attributes and Methods

An object in Python has attributes and methods. 

- **attribute**: don't have parentheses
- **method**: have aparentheses

### Fish attributes:
- length
- color
- species

### Fish methods:
- die(), bite(), swim()

**Example** 
Attributes for `numpy.arrays`

We can access a variables attributes and methods by adding a period at the end of the variable's name.
`variable.method()`, `variable.attrbiute`

In [14]:
a.shape

(2, 3)

In [15]:
type(a.shape)

tuple

In [16]:
# Method examples
#min returns the minimum value along a specified axis.
a.min(axis=0)

array([1, 1, 2])

## Check-in 
We can also call the min method without any parameters

In [17]:
a.min() #The optional argument is 

1

Remember: methods are functions associated with an object. 

In [18]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the type of argument `sep`? Optional/Non-optional? Why?
2. Create two new variables, one with the integer value 77 and another with string 99. 
3. Use your variables to print `77%99%77` by changing the value of one of the optional arguments in `print`. 

In [19]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

The `sep` argument is of type string and is optional. It's default is to add a space between values. 

In [20]:
num1 = 77

In [22]:
num2 = '99'

In [24]:
print(num1,num2,num1, sep = '%')

77%99%77
